# Generated by Django 3.0.3 on 2020-02-18 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('lastname', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('sex', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=1)),
                ('current_sum', models.IntegerField(default=0)),
                ('users_count', models.IntegerField(default=0)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to='botmain.User', verbose_name='creator id')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasker', to='botmain.User', verbose_name='selected user')),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('donater_id', models.ManyToManyField(to='botmain.User', verbose_name='donater')),
                ('task_id', models.ManyToManyField(to='botmain.Task', verbose_name='task')),
            ],
        ),
    ]
