# Generated by Django 3.0.3 on 2020-02-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0005_auto_20200218_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='agee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='t_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tasker_d',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
