# Generated by Django 3.0.3 on 2020-02-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0007_auto_20200218_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='current_sum',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='users_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
