# Generated by Django 3.0.3 on 2020-02-18 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0008_auto_20200218_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
