# Generated by Django 3.0.3 on 2020-02-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0009_auto_20200218_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
