# Generated by Django 3.0.3 on 2020-02-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0010_user_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_button', models.CharField(max_length=55)),
                ('second_button', models.CharField(max_length=55)),
                ('third_button', models.CharField(max_length=55)),
                ('fourth_button', models.CharField(max_length=55)),
                ('fifth_button', models.CharField(max_length=55)),
                ('sixth_button', models.CharField(max_length=55)),
                ('seventh_button', models.CharField(max_length=55)),
                ('eighth_button', models.CharField(max_length=55)),
            ],
        ),
    ]
