# Generated by Django 3.0.3 on 2020-02-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0011_button'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='button',
            options={'verbose_name': 'Кнопка', 'verbose_name_plural': 'Кнопки'},
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
