# Generated by Django 3.0.3 on 2020-02-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0013_auto_20200219_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ManyToManyField(to='botmain.Task', verbose_name='tasks')),
                ('user_id', models.ManyToManyField(to='botmain.User', verbose_name='makers')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
    ]
