# Generated by Django 3.0.3 on 2020-02-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0015_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
