# Generated by Django 3.0.3 on 2020-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0016_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
