# Generated by Django 3.0.3 on 2020-02-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0020_auto_20200224_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
