# Generated by Django 3.0.3 on 2020-02-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0021_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.IntegerField()),
                ('text', models.TextField()),
                ('answer', models.TextField(null=True)),
                ('telegram_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='botmain.Chat', verbose_name='chat')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
