# Generated by Django 3.0.3 on 2020-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0022_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='telegram_id',
            field=models.IntegerField(),
        ),
    ]
